language: php
warnings_are_errors: false
sudo: false

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"
    - COMPOSER_MEMORY_LIMIT=4G

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION="~2.8.0"
    - php: 5.6
      env: SYMFONY_VERSION="~3.0.0"
    - php: 5.6
      env: SYMFONY_VERSION="~3.4.0"
    - php: 7.2
      env: SYMFONY_VERSION="^4.0"
    - php: nightly
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm && -f xdebug.ini ]]; then phpenv config-rm xdebug.ini; fi
  - if [ "$GITHUB_OAUTH_TOKEN" != "" ]; then echo -e $GITHUB_OAUTH_TOKEN && composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - vendor/bin/simple-phpunit
